### ISSUE TITLE
Thanks for your time in writing this. Can you also create a code to carry out purchase, sale, and snipe transactions?

### ISSUE THREAD

**Issue by Othmantork** [franco-bianco/solanaswap-go#11]
Thanks for your time in writing this. Can you also create a code to carry out purchase, sale, and snipe transactions?

**Comment by ziyeziye** [comment]
> Thanks for your time in writing this. Can you also create a code to carry out purchase, sale, and snipe transactions?

I have implemented the function you mentioned, but the trading rules need to be improved. I conducted wallet tracking transactions, but they are very bad. Purposely buying low-volume coins to lure others (robots) to follow the purchase, and then quickly sell them to achieve the purpose of harvesting stalkers for profit. This risk needs to be considered.
